### ISSUE TITLE
the problem of the BM layer

### ISSUE THREAD

**Issue by JJBOY** [xlliu7/BMN-Boundary-Matching-Network#1]
# feature [bs*C, T]
# smp_w    [T, N*D*T]
# out      [bs*C, N*D*T] --> [bs, C, N, D, T]
 result = torch.matmul(X_view, self.smp_weight)

你这样的先view之后再矩阵乘跟原来要表达的意思是不一样的，你可以手算演示一下

**Comment by xlliu7** [comment]
我这里做矩阵相乘是实现线性插值，针对每个temporal location上的D个ROI中的N个采样点，根据其坐标计算在原feature sequence上各个位置的采样权重，如果坐标是整数的话，只对一个位置有非零权重，采样的weight是one-hot的，否则会用插值的方法计算对相邻两个整数位置的权重，然后把两个位置的特征加权求和。用矩阵相乘的话，就是完成了先乘上weight，再求和的过程。用矩阵乘法实现的话就不需要写CUDA了。你说的问题是什么呢？我有点疑惑

**Comment by JJBOY** [comment]
我的意思是你实现的矩阵乘法的方式不能达到你的预期目标。咱们可以加个好友聊一下，不能画图不好表达

**Comment by xlliu7** [comment]
wechat bruce-lio
